### ISSUE TITLE
error about install

### ISSUE THREAD

**Issue by yanqian123** [vita-epfl/openpifpafwebdemo#12]
thanks a lot about share your work ,when i install openpifpafwebdemo, it always make my computer crash, so if the commend line "pip3 install ..." is wrong, or there are some other ways to install it? i am looking for your reply
thanks a lot

**Comment by svenkreiss** [comment]
Did you get to the bottom of this or still have that problem?
I really don't know how it could crash a computer. Do you have very little memory?
