### ISSUE TITLE
Run Video

### ISSUE THREAD

**Issue by HenriqueLeal** [vita-epfl/openpifpafwebdemo#14]
Hi, how I can run a video using pifpaf? Not a webcam video, just a video file.

Thanks

**Comment by svenkreiss** [comment]
Thanks for your interest. The readme has a section for video. Does that
help?

**Comment by svenkreiss** [comment]
The readme of OpenPifPaf: https://github.com/vita-epfl/openpifpaf

**Comment by HenriqueLeal** [comment]
Thanks @svenkreiss for your reply, but when I run this step "python3 -m openpifpaf.predict --checkpoint resnet152 ${VIDEO}.images/*.jpg" the terminal show this message "FileNotFoundError: [Errno 2] No such file or directory: 'resnet152' "

You know whats happen? Please.

Thank you again.

**Comment by HenriqueLeal** [comment]
I solved this one, thank you for the support, really appreciate your job

**Comment by svenkreiss** [comment]
All the best for your project!
