### ISSUE TITLE
low fps on Mac15 pro

### ISSUE THREAD

**Issue by IQ17** [vita-epfl/openpifpafwebdemo#19]
Hi, I tried your webdemo https://vita-epfl.github.io/openpifpafwebdemo/ , but the FPS is only  2-3, which is much lower than the value in your readme.  

Of course there is no cuda on mac, but is there any method to get higher fps?  The model was Resnet18.

**Comment by svenkreiss** [comment]
This is a version that runs entirely in JavaScript in the browser for demo
purposes.
The numbers in the readme are for the main Python version.

**Comment by IQ17** [comment]
aha, that is the JavaScript version version. Thanks!
