### ISSUE TITLE
keypoint_sets dynamic size

### ISSUE THREAD

**Issue by batuhanaman** [vita-epfl/openpifpafwebdemo#21]
Hi,

First of all, thanks for such kind of valuable work. 

I have a question regarding the keypoint_sets size. In my experimental evaluations, I see that the size dynamically changes. Normally, I expect to see an array of size 17 and each represents the joint points.To better represent the problem please refer to screenshot (js console) attached.
<img width="598" alt="Screen Shot 2020-04-02 at 11 25 53 AM" src="https://user-images.githubusercontent.com/44001332/78284856-d98ce600-74d4-11ea-852f-ce176b75d008.png">

In the current implementation, different joint points are presented in different coordinates objects. Is that normal or am I missing something? Is there a way of getting all joint points at once? Or do I need to this programmatically (union of coordinates objects?) Thanks.

**Comment by svenkreiss** [comment]
The number of the people is dynamic. You seem to have an image of three people, so you get 3x a set of coordinates each containing 17 joints.

**Comment by batuhanaman** [comment]
Hi Sven,

Thanks for your answer. I see your points. In my case, I am the only person in the image but the system cannot associate the joint parts with existing ones and represents me as 3 joint sets. That is the coordinates in detection_id 0 has the joint parts nose, eye and ear and the detection_id 1 has just one joint point elbow. Thanks for explanation.
